version: "2"
services:
  database-dev:
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password2018

  wordpress-dev:
    image: wordpress
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8080:80"
    links:
      - database-dev:mysql
    environment:
      WORDPRESS_DB_PASSWORD: Password2018
