# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/stretch64"

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get upgrade -y
     apt-get install -y git
  SHELL

  # The following will install docker CE 17.03 (compat with k8)
  config.vm.provision "shell", inline: <<-MASTERSHELL
    apt-get update
    apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    add-apt-repository \
    "deb https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
    $(lsb_release -cs) \
    stable"
    apt-get update && apt-get install -y docker-ce=$(apt-cache madison docker-ce | grep 17.03 | head -1 | awk '{print $3}')
    apt-mark hold docker-ce
  MASTERSHELL

  config.vm.define "master" do |master|
    master.vm.box = "debian/stretch64"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.1.210"
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "debian/stretch64"
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "192.168.1.211"
  end

  config.vm.define "vm3" do |vm3|
    vm3.vm.box = "debian/stretch64"
    vm3.vm.hostname = "vm3"
    vm3.vm.network "private_network", ip: "192.168.1.212"
  end
end
